//FOODS ACTIONS
export const LOAD_FOODS = 'LOAD_FOODS'
export  const NO_MATCH_FOUND = 'NO_MATCH_FOUND'

export const GET_FOODS_SUCCESS = 'GET_FOODS_SUCCESS'
export const SORT_FOODS = 'SORT_FOODS'
export const SEARCH_FOODS = 'SEARCH_FOODS'
export const GET_FOODS_BEGIN = 'GET_FOODS_BEGIN'
export const GET_FOODS_ERROR = 'GET_FOODS_ERROR'
export const GET_SINGLE_FOOD_SUCCESS = 'GET_SINGLE_FOOD_SUCCESS'
export const GET_SINGLE_FOOD_BEGIN = 'GET_SINGLE_FOOD_BEGIN'
export const GET_SINGLE_FOOD_ERROR = 'GET_SINGLE_FOOD_ERROR'
//CART ACTIONS
export const COUNT_SINGLE_FOOD_QUANTITY = 'COUNT_SINGLE_FOOD_QUANTITY'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const CLEAR_CART = 'CLEAR_CART'
export const COUNT_CART_TOTALS = 'COUNT_CART_TOTALS'
//USER ACTIONS
export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOG_OUT_USER = 'LOG_OUT_USER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_ERROR = 'REGISTER_ERROR'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_ERROR = 'LOGOUT_USER_ERROR'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_ERROR'
export const REGISTER_BEGIN = 'REGISTER_BEGIN'
//SINGLE USER ACTIONS
export const GET_SINGLE_USER_BEGIN = 'GET_SINGLE_USER_BEGIN'
export const SINGLE_USER_UPDATE_SUCCESS = 'SINGLE_USER_UPDATE_SUCCESS'
export const SINGLE_USER_UPDATE_ERROR = 'SINGLE_USER_UPDATE_ERROR'
//ORDER ACTIONS

export const CREATE_ORDER_BEGIN = 'CREATE_ORDER_BEGIN'
export const CREATE_ORDER = 'CREATE_ORDER'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR'
export const UPDATE_SORT = 'UPDATE_SORT'

//ADMIN ACTIONS
export const CREATE_SINGLE_FOOD_SUCCESS = 'CREATE_SINGLE_FOODS_SUCCESS'

export const GET_ALL_ORDERS = 'GET_ALL_ORDERS'
export const GET_ALL_PAYMENTS = 'GET_ALL_PAYMENTS'
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_ALL_FOODS = 'GET_ALL_FOODS'
export const UPDATE_SINGLE_FOOD = 'UPDATE_SINGLE_FOOD'
export const PROCESS_PAYMENT = 'PROCESS_PAYMENT'
export const SINGLE_USER_SUCCESS = 'SINGLE_USER_SUCCESS'
// SINGLE_USER_SUCCESS
export const SINGLE_USER_ERROR = 'SINGLE_USER_ERROR'
//ACTIONS SUCCESS
export const GET_SINGLE_ORDER_SUCCESS = 'GET_SINGLE_ORDER_SUCCESS'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_PAYMENTS_SUCCESS = 'GET_ALL_PAYMENTS_SUCCESS'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_FOODS_SUCCESS = 'GET_ALL_FOODS_SUCCESS'
export const GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS'
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS'
//ACTIONS ERROR
export const GET_SINGLE_ORDER_ERROR = 'GET_SINGLE_ORDER_ERROR'
export const CREATE_SINGLE_FOOD_ERROR = 'CREATE_SINGLE_FOOD_ERROR'
// export const GET_IMAGES_ERROR = 'GET_IMAGES_ERROR'

export const GET_IMAGES_ERROR = 'GET_IMAGES_ERROR'
export const GET_ALL_ORDERS_ERROR = 'GET_ALL_ORDERS_ERROR'
export const GET_ALL_PAYMENTS_ERROR = 'GET_ALL_PAYMENTS_ERROR'
export const GET_ALL_USERS_ERROR = 'GET_ALL_USERS_ERROR'
export const GET_SINGLE_USER_ERROR = 'GET_SINGLE_USER_ERROR'
